"""Fixed JSON issue in Shoppinglist model

Revision ID: 7bf2d5cd6d2e
Revises: e7116532c031
Create Date: 2025-01-31 07:23:11.132896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bf2d5cd6d2e'
down_revision = 'e7116532c031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', postgresql.JSON(astext_type=Text()), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=128), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('items')

    # ### end Alembic commands ###
